### ISSUE TITLE
Blockchain library comparison: Web3.js vs. Ethers.js[PROPOSAL]

### ISSUE THREAD

**Issue by danielonugha0** [chainstacklabs/developer-hub-content#107]
- Content is: Informational content
Here is the link to the article i would love to write on your blog: https://www.dropbox.com/scl/fi/e7ut4qf1nflvrq14kjt9k/Blockchain-library-comparison-Web3.js-vs.-Ethers.js.paper?dl=0&rlkey=rauspdoelfoda81v0w7jbedqf

**Comment by danielonugha0** [comment]
Blockchain is a decentralized and distributed digital ledger technology that allows multiple parties to share and maintain a tamper-evident and transparent record of transactions or information.

[Web3.js ](https://web3js.readthedocs.io/en/v1.8.2/)is a JavaScript library that allows developers to interact with the Ethereum blockchain using HTTP or WebSocket connections. It provides a set of APIs that enable developers to build decentralized applications (dApps) that can read and write to the blockchain.

[Ethers.js](https://www.npmjs.com/package/ethers) is a modern JavaScript library that provides a simple and intuitive way to interact with the Ethereum blockchain. It is designed to be easy to use, fast, and secure, and provides a set of APIs for developers to interact with the Ethereum blockchain and build decentralized applications (dApps).

Goal
There are several blockchain libraries available for developers who want to build applications or systems that utilize blockchain technology but I will be talking about web3.js and Ethers.js which are the two popular ETH libraries.

Table of Content

- Introduction
- Javascript for Blockchain
- What is Ethers.js
- Features of Ethers.js
- Pros and Cons of Ethers.js
- Modules of Ethers.js
- What is Web3.js
- Features of Web3.js
- Pros and Cons of Web3.js
- Modules of Web3.js
- Comparison of Web3.js and Ethers.js
   -Developer experience
   -Popularity
   -Documentation
   -Ease of use
   -Performance
   -Maintenance
- Conclusion

https://dev.to/danielonugha0/building-a-login-system-using-redux-5ce3
https://dev.to/danielonugha0/configuring-worker-plugins-in-vite-28-5dic
https://dev.to/danielonugha0/react-management-hook-vs-redux-3c32

**Comment by Genesis3800** [comment]
Hey @danielonugha0 ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.

As of now we are looking to add coding content on our blog on newer web3 tech.
