### ISSUE TITLE
[PROPOSAL] Native Web3 interface for developers and users with NEAR  protocol integration 

### ISSUE THREAD

**Issue by extravaganza77** [chainstacklabs/developer-hub-content#108]
- Content is:
  [X] Coding tutorial
  [X] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: 
     NEAR

- Description (two or three phrases describing what is it about):
The Web3 interface is a collection of protocols, libraries, and APIs that allow developers to interact with decentralized applications. It provides a standardized set of functions for communicating with the blockchain, including reading and writing data to the blockchain, sending transactions, and interacting with smart contracts. The Web3 interface is designed to be platform-independent, which means it can be used with any blockchain platform that supports it.

The Web3 library provides many features that allow developers to interact with the NEAR blockchain, including:
Connection to the NEAR network:
Developers can use the Web3 library to connect to her NEAR network and start interacting with the blockchain.
Reading data from blockchain:
Developers can use the Web3 library to read data from the NEAR blockchain, including account balances, transaction history, and smart contract data.
Writing data to the blockchain:
Developers can use the Web3 library to write data to the NEAR blockchain, including creating new accounts, submitting transactions, and deploying smart contracts.
Interaction with smart contracts:
Developers can use her Web3 library to manipulate smart contracts on the NEAR blockchain, including calling contract methods and reading contract status. 

- Have you published articles in a blog before? If so, please include some links below 👇
- https://newtosage.hashnode.dev/ethereum-and-optimism-integrate-with-the-pyth-network-to-unlock-hifi-data-for-developers-pyths-data-sourced-from-80-data-feeds-is-now-directly-a
- https://www.section.io/engineering-education/how-to-troubleshoot-and-monitor-a-database/
- https://www.section.io/engineering-education/integration-of-ros-with-arduino/

**Comment by Genesis3800** [comment]
Hey @extravaganza77 ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.

You can take a look at the repo's README for a better idea.
