### ISSUE TITLE
[PROPOSAL]"Radicle: Embracing Decentralization as an alternative to GitHub"

### ISSUE THREAD

**Issue by BRIAN721** [chainstacklabs/developer-hub-content#115]
- Content is:
  [ ] Coding tutorial
  [*] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?: Ethereum

- Description (two or three phrases describing what is it about):
  -  Why Radicle?
  - Radicle Link
  - Radicle vs GitHub
  - Using Radicle:
    - Creating Projects
    - Viewing Open-Source Projects
    - Contributing to Open-Source Projects

- Have you published articles in a blog before? If so, please include some links below 👇
https://medium.com/@briannyamache1/understanding-the-re-entrancy-attacks-in-smart-contracts-9dc9b847355e

**Comment by soos3d** [comment]
Hi!Thank you for your proposal, but we are not looking for this kind of content at the moment. Thank you!😄

**Comment by Bravinsimiyu** [comment]
Hello, what kind of content are you looking for? Like topics and areas to write.

Thanks
@soos3d
