### ISSUE TITLE
[PROPOSAL]How SuperNets can upgrade using Polygon's Chain Development Kits(CDKs)**

### ISSUE THREAD

**Issue by Etimfon007** [chainstacklabs/developer-hub-content#138]
- Content is:  
  [x] Informational content: **How SuperNets can upgrade using Polygon's Chain Development Kits(CDKs)**

- Which blockchain protocol is this about?: **Polygon**

- Description (two or three phrases describing what it is about):   **This article would be focused on developers who are potentially interested in scaling their chains into powered L2s on Ethereum, First of all, an emphasis on why Zero-knowledge proof should be adopted would be laid and how SuperNets can upgrade from L1s to L2s on the Ethereum network.**

**Additionally, I will highlight the potential benefits of SuperNets' connections with other chains, particularly Polygon, in facilitating cross-chain transactions and I'll show ways through a how-to guide in the article on how chains can be designed with code snippets and configurations for easy scaling to be part of the Polygon 2.0 evolution.**

- Have you published articles in a blog before? If so, please include some links below 👇

  - https://timsage.hashnode.dev/account-abstraction
  - https://timsage.hashnode.dev/the-concept-of-blockchain-oracles
  - https://timsage.hashnode.dev/how-to-add-blockchain-testnets-into-a-metamask-wallet
  - https://medium.com/@timsagedev.polygon/an-extensive-onchain-analytic-view-on-the-solana-ecosystem-ce480025ccec
  - https://medium.com/coinsbench/token-standard-erc-20-vs-erc-721-vs-erc-1155-ccbef85f4063

**Comment by akegaviar** [comment]
Okay, thanks a lot for the submission. For now, I don't have any major feedback other than I like the proposal and want to see it come to life and get published. Do you want to do an outline first or just start with a draft? Whichever way, I'm here to help & feedback.

**Comment by Etimfon007** [comment]
Thank you @akegaviar . I'll be starting with an outline though. I'll share with you on my progress.
