### ISSUE TITLE
[PROPOSAL] Use Ethereum's Semaphore to Build a Web 3 Version of Battleship

### ISSUE THREAD

**Issue by TobeTek** [chainstacklabs/developer-hub-content#49]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
**Ethereum**

- Description (two or three phrases describing what is it about):
  - What are Zero-Knowledge-Proofs (ZKPs)?
  - What is Semaphore?
  - Rules of the Game. Why is Privacy important in this Game?
  - Setting Up Semaphore
  - Building the User Interface
  - Writing the Smart Contract
  - Adding Privacy to our Game with Semaphore
  - Conclusion

- Have you published articles in a blog before? If so, please include some links below 👇

   - https://blog.devgenius.io/creating-asynchronous-web-requests-with-python-asyncio-aiohttp-d5469d37cc23
   - https://awstip.com/querying-djangos-jsonfield-a2914f5d4b91
   - https://medium.com/dev-genius/how-to-profile-and-benchmark-python-code-e82a22a2a72c

**Comment by Genesis3800** [comment]
Hey @TobeTek ,
Thank you for creating an issue on the developer hub.
We are glad to have you here.
I have a few questions before I proceed further on this proposal.

1. Where will you be deploying the smart contract?
2. Is semaphore being used in any major projects as of now?
3. How is it different from Zk projects like Polygon and ZkSync have?

**Comment by TobeTek** [comment]
Hello @Genesis3800, 
Thanks for responding.

1. While there are no EIPs that specifically mention Semaphore (after quite a bit of searching ), there are a number of them that center around privacy and privacy enchancing techniques:
   - [ERC-1922: zk-SNARK Verifier Standard](https://eips.ethereum.org/EIPS/eip-1922)
   - [ERC-1387: Merkle Tree Attestations with Privacy enabled](https://eips.ethereum.org/EIPS/eip-1387)
   I'll add a brief summary of the two to the article. A possible future topic could be building Merkle Trees and zkSNARKS with [`circom`](https://docs.circom.io/)?

2. Yes. I've been able to find a few e g [Unirep](https://mobile.twitter.com/shreyjaineth/status/1590310990876659712)
3. Technically, Semaphore can run on any EVM-compatible chain. Polygon however goes further to offer native support for Rollups (Hermez 2.0)

Just to confirm, the next step would be to start writing the actual article?

**Comment by TobeTek** [comment]
Sure @Genesis3800. You can add me on Discord: `Tobe#3032`. Looking forward to hearing from you.

**Comment by Genesis3800** [comment]
Sent you a Friend request from SoulGenesis (He/Him)#9153

**Comment by Genesis3800** [comment]
Issue approved.
Best of luck for the article @TobeTek . We look forward to seeing the first draft.

**Comment by TobeTek** [comment]
Hello @Genesis3800 👋
Been quite a while. I must start off by apologizing for my extremely tardy reply. In between work and some bouts of ill health, I'd been unable to work on this.

I've gone ahead to create a PR #98 and looking forward to your review.

In my implementation, I had to make a number of changes.

1. Semaphore didn't quite fit the bill for this use case. I had intended to use Semaphore identities to hide the ship pieces, but I didn't see any deterministic way to guess/reverse if an identity was/is valid. I instead chose to use public-private signatures.
2. Circom. It wasn't needed for this implementation. If possible, in the future,  I'd like to write an article on creating zkSNARKs with circom and snarkjs.

Thanks, and I do hope this meets you well.

**Comment by Genesis3800** [comment]
Hey @TobeTek ,
Thank you for your submission. 
I see that you have had to make some changes to the original parameters of the article we agreed on.

I'll go through your PR and get back to you as soon as I can

**Comment by Genesis3800** [comment]
Hey @TobeTek ,
I'm sorry being late to reply. I have been quite busy.
I went through your article and contracts. I think your writeup is a beautiful piece of work, and I don't use that lightly or very often. I loved the creativity.
I would really like to jump on a call to discuss a few things before I merge the PR.
Can you please schedule a call?

https://calendly.com/priyank-gupta0308/30min

**Comment by TobeTek** [comment]
Hello @Genesis3800

No worries at all, I completely understand how busy things can get.

Many thanks for your comment! I **really** appreciate it 😄.

Regarding scheduling, I would be happy to arrange a meeting with you. However, it seems that the Calendly link is not working at the moment. Please let me know if you have an alternative way to schedule the meeting.

Thanks again!

**Comment by Genesis3800** [comment]
Hey @TobeTek ,
I reconnected my google calender which somehow got disconnected. Please try again and let me know if it still does not work.

**Comment by TobeTek** [comment]
Hello @Genesis3800 ,
I've gone ahead to add the screenshots of the test runs and gas reports.
Thanks again!

**Comment by Genesis3800** [comment]
Hey @TobeTek  ,
Thank you for your contribution to the developer hub.
We appreciate having you with us.
To move forward, please send me your email address.

I, or one of my colleagues, will reach out to you via mail to request your bank details for processing your payment.

**Comment by TobeTek** [comment]
Hello @Genesis3800 ,

Awesome! 
Thank you for making the entire experience enjoyable and efficient. 
It's been a pleasure contributing.

You can reach me at katchyemma@gmail.com.
