### ISSUE TITLE
[PROPOSAL]

### ISSUE THREAD

**Issue by lanacreates** [chainstacklabs/developer-hub-content#96]
- Content is:
  [x] Coding tutorial
  [ ] Informational content
  [ ] Other (describe)

- Which blockchain protocol is this about?:
  Solana

- Description (two or three phrases describing what is it about):
A step-by-step guide on building a DeFi application using the Solana blockchain. The tutorial will cover key concepts such as smart contracts, decentralized data storage, and integration of web3 technologies for an innovative solution.

- Have you published articles in a blog before? If so, please include some links below 👇
-  https://docs.celo.org/pt/blog/tutorials/creating-a-celo-based-non-fungible-token-marketplace
-  https://docs.celo.org/pt/blog/tutorials/creating-a-celo-based-non-fungible-token-marketplace

**Comment by Genesis3800** [comment]
Hey @lanacreates  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add coding content along these lines to our blog right now.
Please feel free to propose more issues.

**Comment by lanacreates** [comment]
Hello @Genesis3800 
Thank you for getting back. What sort of content are you looking to add?

**Comment by lanacreates** [comment]
Hello @Genesis3800 
Thank you for getting back. What sort of content are you looking to add?
