### ISSUE TITLE
[PROPOSAL] An Overview of Different Blockchain Consensus Algorithms

### ISSUE THREAD

**Issue by prince-joel** [chainstacklabs/developer-hub-content#97]
- Content is:
  [x] Informational content
  [ ] Coding tutorial
  [ ] Other (describe)

- Which blockchain protocol is this about?: Different Blockchain Consensus Algorithms

- Description (two or three phrases describing what is it about): 
     - Detailed Overview of different consensus algorithms, 
     - comparison of mechanisms.
     - Advantages and Disadvantages of Each Algorithm

- Have you published articles in a blog before? If so, please include some links below 👇
- https://dev.to/princejoel/building-a-piggy-bank-smart-contract-with-solidity-hka
- https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/
- https://refine.dev/blog/framer-motion-react-animations/

**Comment by Genesis3800** [comment]
Hey @prince-joel  ,
Thank you for adding your proposal to the developer hub.

Unfortunately, we are not looking to add informational content along these lines to our blog right now.
Please feel free to propose more issues.
